name: EventLogExporter .NET 6

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      working-directory: ./OneSTools.EventLog.Exporter
      run: dotnet restore
    - name: Build
      working-directory: ./OneSTools.EventLog.Exporter
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./OneSTools.EventLog.Exporter
      run: dotnet test --no-restore --verbosity normal
